
services:
  postgres:
    image: postgres    
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"         
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - infinivest

  redis:
    image: redis        
    container_name: redis_container
    ports:
      - "6379:6379"         
    volumes:
      - redis_data:/data    
    networks:
      - infinivest

    
volumes:
  postgres_data:            # Volume for PostgreSQL data persistence
  redis_data:               # Volume for Redis data persistence


networks:
  infinivest:
    name: infinivest